name: Keep Alive

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face Space
        run: curl https://pro580-who-global-health-dashboard.hf.space